import turtle

# setup

turtle.shape('turtle')
turtle.speed(50)
turtle.width(2)

# prepare

turtle.penup()
turtle.left(180)
turtle.forward(80)
turtle.right(90)
turtle.pendown()

# Building

turtle.forward(280)
turtle.left(90)
turtle.forward(250)
turtle.left(90)
turtle.forward(550)
turtle.left(90)
turtle.forward(250)
turtle.left(90)
turtle.forward(280)

# finish building
# prepare for windows

turtle.penup()
turtle.forward(220)
turtle.left(90)
turtle.forward(50)
turtle.pendown()

# Windows

turtle.fillcolor('#25B9A8')
turtle.begin_fill()
turtle.forward(50)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.end_fill()

turtle.penup()
turtle.forward(100)
turtle.pendown()

turtle.begin_fill()
turtle.forward(50)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.end_fill()

turtle.penup()
turtle.left(90)
turtle.forward(150)
turtle.left(90)
turtle.forward(100)
turtle.left(180)
turtle.pendown()

turtle.begin_fill()
turtle.forward(50)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.end_fill()

turtle.penup()
turtle.forward(100)
turtle.pendown()

turtle.begin_fill()
turtle.forward(50)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.end_fill()

turtle.penup()
turtle.left(90)
turtle.forward(150)
turtle.left(90)
turtle.forward(100)
turtle.left(180)
turtle.pendown()

turtle.begin_fill()
turtle.forward(50)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.end_fill()

turtle.penup()
turtle.forward(100)
turtle.pendown()

turtle.begin_fill()
turtle.forward(50)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.end_fill()

# finish windows
# prepare for base of buliding

turtle.penup()
turtle.left(90)
turtle.forward(150)
turtle.left(90)
turtle.pendown()

# Base of building

turtle.fillcolor('gray')
turtle.begin_fill()
turtle.forward(150)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(250)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(100)
turtle.end_fill()

# Finish base of building
# prepare for plane

turtle.penup()
turtle.forward(180)
turtle.left(90)
turtle.forward(240)
turtle.right(45)
turtle.pendown()

#Plane body

turtle.forward(75)
turtle.right(45)
turtle.forward(270)
turtle.left(55)
turtle.forward(120)
turtle.right(145)
turtle.forward(204)
turtle.right(90)
turtle.forward(340)
turtle.right(45)
turtle.forward(75)

# Finished plane body
# prepare for wing

turtle.penup()
turtle.right(90)
turtle.forward(75)
turtle.right(45)
turtle.forward(85)
turtle.left(60)
turtle.pendown()

# Wing (right)

turtle.forward(180)
turtle.right(150)
turtle.forward(155)

# Prep for wing 2

turtle.penup()
turtle.forward(107)
turtle.pendown()

# Wing (left)

turtle.forward(155)
turtle.right(150)
turtle.forward(180)

# Finished wings
# prep for windows

turtle.penup()
turtle.left(60)
turtle.forward(45)
turtle.right(90)
turtle.forward(35)
turtle.left(180)
turtle.pendown()

# Build windows

turtle.left(90)
turtle.fillcolor('#71e8f5')
turtle.begin_fill()
turtle.forward(30)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.end_fill()
turtle.penup()
turtle.forward(65)
turtle.right(90)
turtle.pendown()

turtle.left(90)
turtle.fillcolor('#71e8f5')
turtle.begin_fill()
turtle.forward(30)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.end_fill()
turtle.penup()
turtle.forward(65)
turtle.right(90)
turtle.pendown()

turtle.left(90)
turtle.fillcolor('#71e8f5')
turtle.begin_fill()
turtle.forward(30)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.end_fill()
turtle.penup()
turtle.forward(65)
turtle.right(90)
turtle.pendown()

turtle.left(90)
turtle.fillcolor('#71e8f5')
turtle.begin_fill()
turtle.forward(30)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.end_fill()
turtle.penup()
turtle.forward(65)
turtle.right(90)

# Sun

turtle.right(90)
turtle.forward(210)
turtle.right(90)
turtle.forward(220)
turtle.fillcolor('#eb421c')
turtle.pencolor('#f04f2b')
turtle.pendown()
turtle.begin_fill()
turtle.circle(70,360)
turtle.end_fill()

# end of sun
# grass

turtle.fillcolor('#1dab26')
turtle.pencolor('#1dab26')
turtle.right(180)
turtle.penup()
turtle.forward(450)
turtle.right(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(90)
turtle.left(90)
turtle.pendown()
vertical_pixel = 10
horizon_pixel = 5
turtle.begin_fill()
turtle.left(90)
turtle.forward(vertical_pixel)
turtle.right(90)
turtle.forward(horizon_pixel)
turtle.left(90)
turtle.forward(vertical_pixel)
turtle.right(90)
turtle.forward(horizon_pixel)
turtle.left(90)
turtle.forward(vertical_pixel)
turtle.right(90)
turtle.forward(horizon_pixel)
turtle.left(90)
turtle.forward(vertical_pixel)
turtle.right(90)
turtle.forward(horizon_pixel)
turtle.left(90)
turtle.forward(vertical_pixel)
turtle.right(90)
turtle.forward(horizon_pixel)
turtle.right(90)
turtle.forward(vertical_pixel)
turtle.forward(vertical_pixel)
turtle.right(90)
turtle.forward(horizon_pixel)
turtle.left(90)
turtle.forward(vertical_pixel)
turtle.right(90)
turtle.forward(horizon_pixel)
turtle.left(90)
turtle.forward(vertical_pixel)
turtle.right(90)
turtle.forward(horizon_pixel)
turtle.left(90)
turtle.forward(vertical_pixel)
turtle.right(90)
turtle.forward(10)
turtle.end_fill()
turtle.left(180)
turtle.forward(20)

# Loop grass

for _ in range(18):
    turtle.begin_fill()
    turtle.left(90)
    turtle.forward(vertical_pixel)
    turtle.right(90)
    turtle.forward(horizon_pixel)
    turtle.left(90)
    turtle.forward(vertical_pixel)
    turtle.right(90)
    turtle.forward(horizon_pixel)
    turtle.left(90)
    turtle.forward(vertical_pixel)
    turtle.right(90)
    turtle.forward(horizon_pixel)
    turtle.left(90)
    turtle.forward(vertical_pixel)
    turtle.right(90)
    turtle.forward(horizon_pixel)
    turtle.left(90)
    turtle.forward(vertical_pixel)
    turtle.right(90)
    turtle.forward(horizon_pixel)
    turtle.right(90)
    turtle.forward(vertical_pixel)
    turtle.forward(vertical_pixel)
    turtle.right(90)
    turtle.forward(horizon_pixel)
    turtle.left(90)
    turtle.forward(vertical_pixel)
    turtle.right(90)
    turtle.forward(horizon_pixel)
    turtle.left(90)
    turtle.forward(vertical_pixel)
    turtle.right(90)
    turtle.forward(horizon_pixel)
    turtle.left(90)
    turtle.forward(vertical_pixel)
    turtle.right(90)
    turtle.forward(10)
    turtle.end_fill()
    turtle.left(180)
    turtle.forward(20)

# prep for stars

turtle.penup()
turtle.home()

# Stars

turtle.forward(220)
turtle.left(90)
turtle.forward(150)
turtle.pencolor('yellow')
turtle.fillcolor('yellow')
turtle.pendown()
turtle.begin_fill()
turtle.circle(5,360)
turtle.end_fill()
turtle.penup()
turtle.right(90)
turtle.forward(80)
turtle.left(90)
turtle.forward(20)
turtle.pendown()
turtle.begin_fill()
turtle.circle(10,360)
turtle.end_fill()
turtle.penup()
turtle.left(90)
turtle.forward(15)
turtle.right(90)
turtle.forward(30)
turtle.pendown()
turtle.begin_fill()
turtle.circle(10,360)
turtle.end_fill()

# End of stars

turtle.hideturtle()
turtle.mainloop()